# action.yml
name: 'Publish to Rubygems (configurable)'
description: 'Publish your gem to Rubygems, fully configurable'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'box'
  color: 'red'
